language: python

python:
  - 3.7

sudo: required

services:
  - mysql

install:
  -  sudo apt-get update
  -  sudo apt-get install nginx
  -  pip install -r requirements.txt
  -  pip install pylint
  -  pip install coveralls

script:
#  - pylint **/*.py
  - sudo /home/travis/virtualenv/python3.7.1/bin/python3.7 setup.py
  - coverage run --omit '*/lib/*' -m unittest discover

after_success:
  - coveralls
