language: python

python:
  - 3.7

dist: bionic

sudo: required

services:
  - mysql

install:
  - sudo apt-get update
  - sudo apt-get install nginx

  - sudo pip install -r requirements.txt
  - sudo pip install pylint
  - sudo pip install coveralls

script:
#  - pylint **/*.py
  - sudo python setup.py
  - sudo coverage run --omit '*/lib/*' -m unittest discover

after_success:
  - sudo coveralls
