language: python

python:
  - 3.7

services:
  - mysql

install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install coveralls
  - python create_database.py

script:
  - echo "skipping tests"

after_success:
  - coveralls
