language: python

python:
  - 3.7

services:
  - mysql

install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install coveralls

script:
  - pylint **/*.py
  - python db_setup.py connect
  - python db_setup.py db init
  - python db_setup.py db migrate
  - python db_setup.py db upgrade
  - python db_setup.py seed
  - coverage run --omit '*/lib/*' -m unittest discover

after_success:
  - coveralls
