language: python

python:
  - 3.7

services:
  - mysql

install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install coveralls

script:
#  - pylint **/*.py
  - python sudo setup.py
  - coverage run --omit '*/lib/*' -m unittest discover

after_success:
  - coveralls
